const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const regionKo={Asia:'아시아',Europe:'유럽',Africa:'아프리카',Americas:'아메리카',Oceania:'오세아니아',Antarctic:'남극'};
const sources={NP:{status:'live',name:'Books Mandala',scope:'Books Mandala 베스트셀러 판매 순위',url:'https://booksmandala.com/best-sellers'}};
const knownTitles={'Atomic Habits':['아주 작은 습관의 힘','공식 한국어판'],'Crime and Punishment':['죄와 벌','공식 한국어판'],'White Nights':['백야','공식 한국어판'],'Think and Grow Rich':['생각하라 그리고 부자가 되어라','공식 한국어판'],'The Brothers Karamazov':['카라마조프가의 형제들','공식 한국어판'],'Rich Dad Poor Dad':['부자 아빠 가난한 아빠','공식 한국어판'],'Kafka on the Shore':['해변의 카프카','공식 한국어판'],"Man's Search For Meaning":['죽음의 수용소에서','공식 한국어판'],'When Breath Becomes Air':['숨결이 바람 될 때','공식 한국어판'],'Ikigai':['이키가이','참고 표기'],'Karnali Blues':['카르날리 블루스','참고 번역']};
const authorKo={'James Clear':'제임스 클리어','Robert Greene':'로버트 그린','Fyodor Dostoyevsky':'표도르 도스토옙스키','Viktor E Frankl':'빅터 프랭클','Paul Kalanithi':'폴 칼라니티','Haruki Murakami':'무라카미 하루키','Napoleon Hill':'나폴레온 힐','Buddhisagar':'부디사가르'};
const localNepal=new Set(['Buddhisagar','Purushottam Bajagai','Bibek Ojha','Amar Neupane','Subin Bhattarai','Narayan Wagle','Parijat']);
const fallbackNepal=[['Atomic Habits','James Clear'],['The 48 Laws of Power','Robert Greene'],['Karnali Blues','Buddhisagar'],['Crime and Punishment','Fyodor Dostoyevsky'],['Usle Diyeko Umer','Buddhisagar'],['Bhagavad Gita As It Is (Nepali Translation ) - Srimad Bhagavad Gita Yatharup','A.C. Bhaktivedanta Swami Prabhupada'],['White Nights','Fyodor Dostoyevsky'],['Nilo Prem','Purushottam Bajagai'],['Too Good to Be True','Prajakta Koli'],['Ikigai','Hector Garcia Puigcerver'],['Eklo','Buddhisagar'],['Aaithan','Bibek Ojha'],["I Don't Love You Anymore",'Rithvik Singh'],['Phirphirey','Buddhisagar'],['Seto Dharti','Amar Neupane'],['The Personal MBA','Josh Kaufman'],['Think and Grow Rich','Napoleon Hill'],['Ijoriya','Subin Bhattarai'],['Palpasa Cafe','Narayan Wagle']].map(x=>({title:x[0],author:x[1]}));
let countries=[],selected=null,region='all',filter='all',books=[],globeObj=null;
function flag(code){return [...code].map(c=>String.fromCodePoint(127397+c.charCodeAt())).join('')}
function toast(t){const n=$('#toast');n.textContent=t;n.style.display='block';clearTimeout(n._t);n._t=setTimeout(()=>n.style.display='none',2200)}
function esc(s=''){return String(s).replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]))}
async function loadCountries(){try{const u='https://restcountries.com/v3.1/all?fields=name,cca2,capital,capitalInfo,latlng,region,subregion,unMember,independent,translations';const r=await fetch(u);if(!r.ok)throw 0;const d=await r.json();countries=d.filter(c=>c.cca2&&(c.unMember||c.independent)).map(c=>({code:c.cca2,nameKo:c.translations?.kor?.common||c.name.common,name:c.name.common,flag:flag(c.cca2),capital:c.capital?.[0]||'',region:c.region||'',lat:(c.capitalInfo?.latlng||c.latlng||[])[0],lng:(c.capitalInfo?.latlng||c.latlng||[])[1]})).sort((a,b)=>a.nameKo.localeCompare(b.nameKo,'ko'));}catch(e){countries=[{code:'NP',nameKo:'네팔',name:'Nepal',flag:'🇳🇵',capital:'Kathmandu',region:'Asia',lat:27.7,lng:85.3},{code:'KR',nameKo:'한국',name:'South Korea',flag:'🇰🇷',capital:'Seoul',region:'Asia',lat:37.5,lng:127},{code:'JP',nameKo:'일본',name:'Japan',flag:'🇯🇵',capital:'Tokyo',region:'Asia',lat:35.6,lng:139.7},{code:'US',nameKo:'미국',name:'United States',flag:'🇺🇸',capital:'Washington, D.C.',region:'Americas',lat:38.9,lng:-77}];toast('국가 목록 연결이 느려 기본 목록을 먼저 보여드려요.');}
$('#worldCount').textContent=`전 세계 ${countries.length}개국을 여행할 수 있어요.`;renderRegions();renderCountries();initGlobe();const q=new URLSearchParams(location.search).get('country')?.toUpperCase();selectCountry(countries.find(c=>c.code===q)||countries.find(c=>c.code==='NP')||countries[0],false)}
function renderRegions(){const rs=['all',...new Set(countries.map(c=>c.region).filter(Boolean))];$('#regions').innerHTML=rs.map(r=>`<button class="region ${r===region?'on':''}" data-r="${r}">${r==='all'?'전체':regionKo[r]||r}</button>`).join('');$$('.region').forEach(b=>b.onclick=()=>{region=b.dataset.r;renderRegions();renderCountries()})}
function renderCountries(){const q=$('#countrySearch').value.trim().toLowerCase();const list=countries.filter(c=>(region==='all'||c.region===region)&&(!q||c.nameKo.toLowerCase().includes(q)||c.name.toLowerCase().includes(q)||c.code.toLowerCase().includes(q)));$('#countryGrid').innerHTML=list.map(c=>`<button class="country ${sources[c.code]?.status==='live'?'live':''} ${selected?.code===c.code?'on':''}" data-code="${c.code}"><span class="flag">${c.flag}</span><span class="name">${c.nameKo}</span><i class="status"></i></button>`).join('');$$('.country').forEach(b=>b.onclick=()=>selectCountry(countries.find(c=>c.code===b.dataset.code)))}
function initGlobe(){if(!window.Globe){$('#globeFallback').style.display='block';return}try{const pts=countries.filter(c=>Number.isFinite(c.lat)&&Number.isFinite(c.lng));globeObj=Globe()($('#globe')).backgroundColor('rgba(0,0,0,0)').globeImageUrl('https://unpkg.com/three-globe/example/img/earth-blue-marble.jpg').bumpImageUrl('https://unpkg.com/three-globe/example/img/earth-topology.png').pointsData(pts).pointLat('lat').pointLng('lng').pointAltitude(c=>sources[c.code]?.status==='live'?.06:.025).pointRadius(c=>sources[c.code]?.status==='live'?.32:.16).pointColor(c=>sources[c.code]?.status==='live'?'#67aa80':'#d7ddd7').pointLabel(c=>`<div style="padding:5px 7px;font-family:system-ui"><b>${c.flag} ${c.nameKo}</b><br><small>${sources[c.code]?.status==='live'?'서점 연결됨':'출처 확보 중'}</small></div>`).onPointClick(c=>selectCountry(c));globeObj.controls().autoRotate=true;globeObj.controls().autoRotateSpeed=.35;resizeGlobe();addEventListener('resize',resizeGlobe)}catch(e){$('#globeFallback').style.display='block'}}
function resizeGlobe(){if(!globeObj)return;const e=$('#globe').parentElement,s=Math.min(e.clientWidth,e.clientHeight);globeObj.width(s).height(s)}
function focusGlobe(c){if(globeObj&&Number.isFinite(c.lat)&&Number.isFinite(c.lng))globeObj.pointOfView({lat:c.lat,lng:c.lng,altitude:1.7},800)}
async function selectCountry(c,scroll=true){if(!c)return;selected=c;history.replaceState({},'',`${location.pathname}?country=${c.code}`);renderCountries();focusGlobe(c);$('#countryTitle').textContent=`${c.nameKo}의 서점에 도착했어요.`;$('#place').textContent=`${c.flag} ${c.capital||c.name}, ${c.nameKo}`;if(sources[c.code]){$('#arrivalText').textContent=`${sources[c.code].name}의 공개 판매 순위를 확인합니다.`;$('#sourceMeta').innerHTML=`${sources[c.code].name}<br>최신 확인 중`;$('#notice').textContent=`${sources[c.code].scope}입니다. ${c.nameKo} 전체의 모든 책 판매를 대표하는 국가 공식 순위는 아닙니다.`;$('#filters').style.display='flex';await loadNepal();}else{$('#arrivalText').textContent='신뢰할 수 있는 현지 서점·기관 출처를 찾는 중입니다.';$('#sourceMeta').innerHTML='현지 출처<br>연결 준비 중';$('#notice').textContent='출처가 없는 순위를 임의로 만들지 않아요. 검증된 현지 판매 순위를 확보하기 전까지 책 순위는 열지 않습니다.';$('#filters').style.display='none';renderEmpty(c)}if(scroll)$('#bookstore').scrollIntoView({behavior:'smooth',block:'start'})}
function renderEmpty(c){$('#bookCount').textContent='';$('#content').innerHTML=`<div class="empty"><article class="emptyHero"><div class="kicker">SOURCE CONNECTING</div><h3>${c.flag} ${c.nameKo}의 서점을 연결하고 있어요.</h3><p>Apple Books 유료 차트나 임의의 글로벌 순위로 채우지 않고, 이 나라에서 실제로 쓰이는 서점·출판 유통기관의 공개 순위를 찾고 있습니다.</p><div class="steps"><div class="step"><b>01 · 현지 출처 찾기</b><span>대형 서점·공식 기관·업계 차트 우선</span></div><div class="step"><b>02 · 순위 검증</b><span>기준·갱신일·원문 링크 확인</span></div><div class="step"><b>03 · 한국어로 열기</b><span>제목·작가·설명을 한국어 레이어로 제공</span></div></div><p><button class="primary" id="goNepal">지금 연결된 네팔 서점 보기 →</button></p></article><aside class="passport"><div class="kicker">BOOKSTORE PASSPORT</div><div class="facts"><div class="fact"><small>나라</small><strong>${c.nameKo}</strong></div><div class="fact"><small>수도</small><strong>${c.capital||'확인 중'}</strong></div><div class="fact"><small>지역</small><strong>${regionKo[c.region]||c.region||'확인 중'}</strong></div><div class="fact"><small>상태</small><strong>출처 확보 중</strong></div></div><p>회색 점도 모두 클릭할 수 있어요. 초록 점으로 바뀌는 순간부터 실제 현지 순위를 보여줍니다.</p></aside></div>`;$('#goNepal').onclick=()=>selectCountry(countries.find(x=>x.code==='NP'))}
async function loadNepal(){const loading=$('#loading');loading.style.display='block';let raw=[],live=false;try{const cache=JSON.parse(localStorage.getItem('bm-cache')||'null');if(cache&&Date.now()-cache.t<21600000){raw=cache.books;live=true}else{const r=await fetch('https://r.jina.ai/https://booksmandala.com/best-sellers');if(!r.ok)throw 0;const text=await r.text();raw=parseBooks(text);if(raw.length<5)throw 0;localStorage.setItem('bm-cache',JSON.stringify({t:Date.now(),books:raw}));live=true}}catch(e){raw=fallbackNepal}books=raw.slice(0,20).map((b,i)=>({rank:i+1,title:b.title,author:b.author,local:localNepal.has(cleanAuthor(b.author)),source:'Books Mandala'}));await Promise.all(books.slice(0,12).map(enrichBook));loading.style.display='none';$('#sourceMeta').innerHTML=`Books Mandala<br>${live?'방금 확인':'최근 확인본'} · ${new Date().toLocaleDateString('ko-KR',{month:'2-digit',day:'2-digit'})}`;$('#notice').textContent=live?'Books Mandala 공개 베스트셀러 페이지를 방금 확인했어요. 이 순위는 Books Mandala 판매 기준이며 네팔 전체 서점의 국가 공식 집계는 아닙니다.':'실시간 확인이 잠시 되지 않아 최근 확인된 Books Mandala 목록을 보여드려요.';renderBooks()}
function parseBooks(t){const out=[];for(const line of t.split('\n')){const s=line.replace(/^\s*[-*]\s+/,'').trim();let m=s.match(/^(.+?)\s+by\s+(.+?)\s+(?:—|-{1,2})\s+(?:Rs\.|NPR|\$)/i);if(!m)m=s.match(/^(.+?)\s+by\s+(.+?)\s+—/i);if(m&&m[1].length<140)out.push({title:m[1].trim(),author:m[2].trim()})}return [...new Map(out.map(x=>[x.title.toLowerCase(),x])).values()]}
function cleanAuthor(a){return a.replace(/,.*$/,'').replace(/\s+\(.*?\)/g,'').trim()}
async function enrichBook(b){try{const q=new URLSearchParams({title:b.title,author:cleanAuthor(b.author),limit:'1',fields:'cover_i,first_sentence'}),r=await fetch(`https://openlibrary.org/search.json?${q}`),d=await r.json(),doc=d.docs?.[0];if(doc?.cover_i)b.cover=`https://covers.openlibrary.org/b/id/${doc.cover_i}-L.jpg`;const fs=Array.isArray(doc?.first_sentence)?doc.first_sentence[0]:doc?.first_sentence;if(fs)b.summary=await translateKo(fs)}catch(e){}const k=knownTitles[b.title];if(k){b.ko=k[0];b.koType=k[1]}else b.ko=await translateKo(b.title);b.authorKo=authorKo[cleanAuthor(b.author)]||cleanAuthor(b.author)}
async function translateKo(text){if(!text)return'';try{if('Translator'in self){const a=await Translator.availability({sourceLanguage:'en',targetLanguage:'ko'});if(a!=='unavailable'){const t=await Translator.create({sourceLanguage:'en',targetLanguage:'ko'});return await t.translate(text)}}}catch(e){}return text}
function renderBooks(){let list=filter==='local'?books.filter(b=>b.local):books;$('#bookCount').textContent=`${list.length}권`;$('#content').innerHTML=`<div class="books">${list.map(bookCard).join('')}</div>`;$$('.book img').forEach(img=>{img.onload=()=>{img.style.display='block';img.nextElementSibling.style.display='none'}})}
function bookCard(b){const title=b.ko||b.title,translated=title!==b.title;return `<article class="book"><div class="rank">#${b.rank}</div><div class="cover">${b.cover?`<img src="${b.cover}" alt="${esc(b.title)} 표지" loading="lazy">`:''}<div class="fallback"><small>${selected.flag} ${selected.nameKo}</small><b>${esc(title)}</b><small>BABEL READS</small></div></div><div class="bookbody"><h3>${esc(title)}</h3><div class="orig">${translated?`원제 · ${esc(b.title)} · ${b.koType||'자동 번역'}`:'원제 표기'}</div><span class="author">${esc(b.authorKo||b.author)}</span><p class="summary">${esc(b.summary||'책 소개를 불러오는 중입니다.')}</p><div class="tags">${b.local?'<span class="tag">현지 작가</span>':''}<span class="tag">${esc(b.koType||'한국어 우선')}</span></div></div><div class="src"><span>${b.source} · #${b.rank}</span><a href="${sources.NP.url}" target="_blank" rel="noopener">원본 확인 ↗</a></div></article>`}
$('#countrySearch').addEventListener('input',renderCountries);$('#startBtn').onclick=()=>$('#world').scrollIntoView({behavior:'smooth'});$('#sourcesBtn').onclick=()=>$('#sources').scrollIntoView({behavior:'smooth'});$('#surpriseBtn').onclick=()=>selectCountry(countries[Math.floor(Math.random()*countries.length)]);$('#shareBtn').onclick=async()=>{const u=location.href,t=selected?`${selected.nameKo}의 서점에 같이 가볼래요? — 바벨의 서재`:'바벨의 서재';try{if(navigator.share)await navigator.share({title:t,text:'세계의 서점을 여행하며 현지에서 읽히는 책을 만나보세요.',url:u});else{await navigator.clipboard.writeText(u);toast('링크를 복사했어요.')}}catch(e){}};$('#filters').onclick=e=>{const b=e.target.closest('.filter');if(!b)return;filter=b.dataset.filter;$$('.filter').forEach(x=>x.classList.toggle('on',x===b));renderBooks()};loadCountries();